import {
    DecoderOptions,
    ParsedDecoderOptions,
    ParsedFilterKey
} from "../typings/decoders";
import {
    replaceDoubleBacklash,
    removeEscapeCharacters,
    isAutoGeneratedKey,
} from "../utils/formatters";
import {
    PERIOD_REGEX,
} from "../typings/formatters";

const parseFilterKey = (
    filterKey: string,
): ParsedFilterKey => {
    filterKey = replaceDoubleBacklash(filterKey);
    const isAutoGenerated: boolean = isAutoGeneratedKey(filterKey);
    if (isAutoGenerated) {
        filterKey = filterKey.substring(1);
    }
    let splitKey = filterKey.split(PERIOD_REGEX);
    splitKey = splitKey.map((key) => removeEscapeCharacters(key));
    return {
            isAutoGenerated: isAutoGenerated,
            splitKey: splitKey,
        }
    };

const parseDecoderOptions = (
    decoderOptions: DecoderOptions,
): ParsedDecoderOptions => {
    return {
            formatString: decoderOptions.formatString,
            logLevelKey: parseFilterKey(decoderOptions.logLevelKey),
            timestampKey: parseFilterKey(decoderOptions.timestampKey),
        }
    };

export {
    parseDecoderOptions,
    parseFilterKey
};
