import {Nullable} from "../../../typings/common";
import {
    COLON_REGEX,
    PERIOD_REGEX,
    YscopeFieldFormatterMap,
    YscopeFieldPlaceholder,
} from "../../../typings/formatters";
import {JsonObject} from "../../../typings/js";
import {LogEvent} from "../../../typings/logs";
import {getNestedJsonValue} from "../../../utils/js";
import {
    jsonValueToString,
    removeEscapeCharacters,
    replaceDoubleBacklash,
} from "../../../utils/formatters";
import RoundFormatter from "./FieldFormatters/RoundFormatter";
import TimestampFormatter from "./FieldFormatters/TimestampFormatter";


/**
 * List of currently supported field formatters.
 */
const YSCOPE_FIELD_FORMATTER_MAP: YscopeFieldFormatterMap = Object.freeze({
    timestamp: TimestampFormatter,
    round: RoundFormatter,
});

/**
 * Gets a formatted field. Specifically, retrieves a field from a log event using a placeholder's
 * `fieldNameKeys`. The field is then formatted using the placeholder's `fieldFormatter`.
 *
 * @param logEvent
 * @param fieldPlaceholder
 * @return The formatted field as a string.
 */
const getFormattedField = (
    containsAutoGeneratedKeys: boolean,
    logEvent: LogEvent,
    fieldPlaceholder: YscopeFieldPlaceholder
): string => {

    let fields: JsonObject = logEvent.fields;
    if (containsAutoGeneratedKeys) {
        if (fieldPlaceholder.isAutoGenerated) {
            fields = fields["auto-generated"] as JsonObject;
        } else {
            fields = fields["user-generated"] as JsonObject;
        }
    }

    const nestedValue = getNestedJsonValue(logEvent.fields, fieldPlaceholder.fieldNameKeys);
    if ("undefined" === typeof nestedValue) {
        return "";
    }

    const formattedField = fieldPlaceholder.fieldFormatter ?
        fieldPlaceholder.fieldFormatter.formatField(nestedValue) :
        jsonValueToString(nestedValue);

    return formattedField;
};

/**
 * Validates a component string.
 *
 * @param component
 * @return The component string if valid, or `null` if the component is undefined or empty.
 */
const validateComponent = (component: string | undefined): Nullable<string> => {
    if ("undefined" === typeof component || 0 === component.length) {
        return null;
    }

    return component;
};

/**
 * Splits a field placeholder string into its components: field name, formatter name, and formatter
 * options.
 *
 * @param placeholderString
 * @return - An object containing:
 * - isAutoGenerated: Whether the field name is auto-generated.
 * - fieldNameKeys: An array of strings representing the field name split by periods.
 * - formatterName: The formatter name, or `null` if not provided.
 * - formatterOptions: The formatter options, or `null` if not provided.
 * @throws {Error} If the field name could not be parsed.
 */
const splitFieldPlaceholder = (placeholderString: string, containsAutoGeneratedKeys: boolean): {
    isAutoGenerated: boolean;
    fieldNameKeys: string[];
    formatterName: Nullable<string>;
    formatterOptions: Nullable<string>;
} => {
    let [
        fieldName,
        formatterName,
        formatterOptions,
    ]: Nullable<string | undefined>[
    ] = placeholderString.split(COLON_REGEX, 3);

    fieldName = validateComponent(fieldName);
    if (null === fieldName) {
        throw Error("Field name could not be parsed");
    }

    let isAutoGenerated = false;
    if (containsAutoGeneratedKeys) {
        if (fieldName.charAt(0) == '@') {
            // Note we silently ignore user syntax error for field names with `@` prefix for JSONL files.
            isAutoGenerated = true;
            fieldName = fieldName.substring(1);
        }
    }

    // Splits field name into an array of field name keys to support nested fields.
    let fieldNameKeys = fieldName.split(PERIOD_REGEX);

    fieldNameKeys = fieldNameKeys.map((key) => removeEscapeCharacters(key));

    formatterName = validateComponent(formatterName);
    if (null !== formatterName) {
        formatterName = removeEscapeCharacters(formatterName);
    }

    formatterOptions = validateComponent(formatterOptions);
    if (null !== formatterOptions) {
        formatterOptions = removeEscapeCharacters(formatterOptions);
    }

    return {isAutoGenerated, fieldNameKeys, formatterName, formatterOptions};
};


export {
    getFormattedField,
    jsonValueToString,
    removeEscapeCharacters,
    replaceDoubleBacklash,
    splitFieldPlaceholder,
    YSCOPE_FIELD_FORMATTER_MAP,
};