name: "Deploy to GitHub Pages"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-node@v4"
        with:
          node-version: "22"

      - name: "Get npm cache directory"
        id: "get-npm-cache-dir"
        run: "echo 'dir=$(npm config get cache)' >> ${GITHUB_OUTPUT}"
      - name: "Restore npm cache"
        uses: "actions/cache@v4"
        with:
          path: "${{steps.get-npm-cache-dir.outputs.dir}}"
          key: "${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}"
          restore-keys: |
            ${{runner.os}}-node-

      - run: "npm install"
      - run: "npm run build"

      - name: "Upload static files as artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./dist"

  deploy:
    needs: "build"
    permissions:
      # to deploy to Pages
      pages: "write"
      # to verify the deployment originates from an app
      id-token: "write"
    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{steps.deployment.outputs.page_url}}"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
