name: "test"

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"
      - uses: "actions/setup-node@v4"
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - run: "npm clean-install"
      - run: "npm run test"
